apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  # echo -n 'secretpassword' | base64
  POSTGRES_PASSWORD: c2VjcmV0cGFzc3dvcmQ=
  # echo -n 'postgres' | base64  
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n 'k8s_app' | base64
  POSTGRES_DB: azhzX2FwcA==